# Names: Jarrett Knauer, Rafaella Grana
# Student ID: 
# CMPUT 275, WINTER 2019
#
# Assignment 2, Part 1: Driving Route Finder

CC = g++
LFLAGS = -c -Wall -O2 -std=c++11
CFLAGS =
OBJS =
PROGS =

# executable targets

# object targets

# clean
clean:
	@rm $(PROGS) $(OBJS)