# Names: Jarrett Knauer, Rafaella Grana
# Student ID:
# CMPUT 275, WINTER 2019
#
# Assignment 2, Part 2: Driving Route Finder

CC = g++
LFLAGS = 
CFLAGS = -c -Wall -O2 -std=c++11
OBJS =
PROGS =

# executable targets

# object targets

# clean
clean:
	@rm $(PROGS) $(OBJS)